import json
import sys
from pathlib import Path

sys.path.insert(0, "/tmp/claude-1000/-home-corymaynard370/7daef8aa-b8bb-49b8-8f09-dce1989aa5f0/scratchpad")
from common import must_claims

PACKAGES = {
    "click-8.4.1": "/tmp/dispatch-audit-python-extracted/click-8.4.1/click-8.4.1",
    "pydantic-2.13.4": "/tmp/dispatch-audit-python-extracted/pydantic-2.13.4/pydantic-2.13.4",
    "requests-2.34.2": "/tmp/dispatch-audit-python-extracted/requests-2.34.2/requests-2.34.2",
}
SCRATCH = "/tmp/claude-1000/-home-corymaynard370/7daef8aa-b8bb-49b8-8f09-dce1989aa5f0/scratchpad"

# All 347 claims, with package tagged, plus package root for reading source.
all_claims = []
for pkg, root in PACKAGES.items():
    for c in must_claims(f"{SCRATCH}/{pkg}-inspect-correction1.json"):
        c["pkg"] = pkg
        c["root"] = root
        all_claims.append(c)

# Load the original 20-site sample (drawn from the incomplete 309 population in correction-1).
with open(f"{SCRATCH}/hand_sample.json") as f:
    original_sample = json.load(f)

# Match each original-sample entry to its corrected claim (by caller_file, caller, site_start).
def find_claim(entry):
    for c in all_claims:
        if (
            c["caller_file"] == entry["caller_file"]
            and c["caller"] == entry["caller"]
            and c["site_start"] == entry["site_start"]
        ):
            return c
    return None


matched = []
for entry in original_sample:
    c = find_claim(entry)
    if c is None:
        print("WARNING: could not re-match", entry, file=sys.stderr)
        continue
    matched.append(c)

# Identify the 8 distinct (file, name) targets that were unresolved under the old
# unpadded lookup but are resolved now -- one representative call site each.
# Old (buggy) resolved set, recomputed the same way correction-1's early scripts did.
import re

claim_re = re.compile(
    r"\(site:\([^)]*\),class:(\w+),targets:\[([^\]]*)\],reason:\"([^\"]*)\",coverage_gap:(\w+)\)"
)


def old_buggy_resolved_names(path):
    with open(path) as f:
        data = json.load(f)
    nodes = data["nodes"]
    by_hex = {n["id"]: n for n in nodes}
    names = set()
    for n in nodes:
        for k, v in n.get("attributes", []):
            if k != "call_evidence_v1":
                continue
            for m in claim_re.finditer(v):
                cls, targets_str, reason, cov = m.groups()
                if cls == "must" and reason == "proven-top-level-lexical-binding":
                    for tid in targets_str.split(","):
                        tid = tid.strip().strip("()")
                        if not tid:
                            continue
                        hexid = format(int(tid), "x")  # buggy, unpadded
                        node = by_hex.get(hexid)
                        if node:
                            names.add((node.get("file"), node.get("name")))
    return names


recovered_targets = []
for pkg, root in PACKAGES.items():
    old_names = old_buggy_resolved_names(f"{SCRATCH}/{pkg}-inspect-correction1.json")
    new_names = set((c["target_file"], c["target_name"]) for c in all_claims if c["pkg"] == pkg)
    newly_recovered = new_names - old_names
    for tf, tn in newly_recovered:
        # find one call site targeting this
        for c in all_claims:
            if c["pkg"] == pkg and c["target_file"] == tf and c["target_name"] == tn:
                recovered_targets.append(c)
                break

print(f"# {len(matched)} original-sample sites re-matched, {len(recovered_targets)} recovered-target sites", file=sys.stderr)

lines = []
lines.append("# Hand-read excerpts: original 20-site sample plus the 8 previously-unresolved targets\n")
lines.append(
    "Generated by `generate_excerpts.py` (this directory) -- every site listed here\n"
    "is read directly from the extracted package source (rows N-3..N+3 around the\n"
    "call site's own row), not summarized or paraphrased by hand. Two groups:\n\n"
    "1. The original 20-site sample `correction-1/hand-sample.json` drew, with a\n"
    "   fixed seed, from the (at-the-time incomplete, 309-claim) population --\n"
    "   still 20 genuine members of the corrected 347-claim population, just not\n"
    "   re-randomized against it. Each is re-matched here to its corrected claim\n"
    "   record and read fresh.\n"
    "2. One call site for each of the distinct `(file, name)` targets that the\n"
    "   unpadded hex bug (`correction-2` \\S1) silently dropped from every check\n"
    "   before this generation script -- specifically included so that population\n"
    "   is no longer entirely unread.\n"
)

lines.append("\n## Group 1: original 20-site sample\n")
for i, c in enumerate(matched, 1):
    src_path = Path(c["root"]) / c["caller_file"]
    try:
        src_lines = src_path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as e:
        lines.append(f"\n### {i}. {c['pkg']} {c['caller_file']}::{c['caller']} row {c['row']} -> {c['target_name']}\nCOULD NOT READ SOURCE: {e}\n")
        continue
    row = c["row"]
    start = max(0, row - 3)
    end = min(len(src_lines), row + 4)
    excerpt = "\n".join(src_lines[start:end])
    lines.append(
        f"\n### {i}. {c['pkg']} {c['caller_file']}::{c['caller']} row {c['row']} -> {c['target_file']}::{c['target_name']}\n```python\n{excerpt}\n```\n"
    )

lines.append("\n## Group 2: one site per previously-unresolved target\n")
for i, c in enumerate(recovered_targets, 1):
    src_path = Path(c["root"]) / c["caller_file"]
    try:
        src_lines = src_path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as e:
        lines.append(f"\n### R{i}. {c['pkg']} {c['caller_file']}::{c['caller']} row {c['row']} -> {c['target_name']}\nCOULD NOT READ SOURCE: {e}\n")
        continue
    row = c["row"]
    start = max(0, row - 3)
    end = min(len(src_lines), row + 4)
    excerpt = "\n".join(src_lines[start:end])
    lines.append(
        f"\n### R{i}. {c['pkg']} {c['caller_file']}::{c['caller']} row {c['row']} -> {c['target_file']}::{c['target_name']}\n```python\n{excerpt}\n```\n"
    )

lines.append(f"\n## Totals\n\nGroup 1: {len(matched)} of 20 original-sample sites re-read. Group 2: {len(recovered_targets)} previously-unresolved-target sites read.\n")

with open(f"{SCRATCH}/hand-sample-excerpts-generated.md", "w") as f:
    f.write("".join(lines))
print("wrote", f"{SCRATCH}/hand-sample-excerpts-generated.md")
